apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- svc.yaml
- ingress.yaml
#namespace: quarkus-demo
images:
- name: quarkus-demo
  newName: pzalejko/quarkus-github-actions-demo
  newTag: "38"
